apiVersion: anomalydetection.andreee94.ml/v1alpha1
kind: Datasource
metadata:
  namespace: anomaly-detection
  name: datasource-sample
spec:
  datasourceType: Prometheus
  url: http://prometheus-svc:9090
  isAuthenticated: false
  
  # isAuthenticated: true
  # usernameSecretRef:
  #   name: prometheus-anomaly-detection-user
  #   key: username
  # passwordSecretRef:
  #   name: prometheus-anomaly-detection-user
  #   key: password

  