# permissions for end users to edit trainers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: trainer-editor-role
rules:
- apiGroups:
  - anomalydetection.andreee94.ml
  resources:
  - trainers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - anomalydetection.andreee94.ml
  resources:
  - trainers/status
  verbs:
  - get
