# permissions for end users to view trainers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: trainer-viewer-role
rules:
- apiGroups:
  - anomalydetection.andreee94.ml
  resources:
  - trainers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - anomalydetection.andreee94.ml
  resources:
  - trainers/status
  verbs:
  - get
